### ISSUE TITLE
Small documentation suggestion

### ISSUE THREAD

**Issue by LL25255252** [yuvadm/free-haaretz#18]
First, thanks a lot for fixing the addon. The previous 0.9 version has stopped working lately  and the new 0.9.1 fixed everything.

Only one small suggestion. Add "when upgrading from an older version make sure in the Addons Manager that it was overrided  and if not remove it" to the Troubleshooting segment of the addon homepage (the new 0.9.1 version has a different extension id than the 0.9 version).
Thanks in advance.

**Comment by yuvadm** [comment]
You are correct, there was a bug in the signing process on my side. I will push another release soon `v0.9.2` and will make sure only one proper extension ID is used. Thanks for the feedback.

Also if you see the extension is broken please open an issue, it took me a while to figure out that the bug was due to a behavior change in Firefox that started occuring "randomly" across users.

**Comment by yuvadm** [comment]
Made some final changes and updated `v0.9.3`
